TW/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TW.Models.Database;

namespace TW.Controllers
{
    public class CategoryController : Controller
    {
        //
        // GET: /Category/

        public ActionResult Index( string view, int id = 0)
        {
            IList<Category> categories =  Services.CategoryService.GetAll();
            int[] nodesWithDepth = new int[categories.Max(category1 => category1.Id)+1];
            foreach (Category category in categories)
            {
                int counter = 0;
                foreach (Category category2 in categories)
                {
                    if (category2.Lft < category.Lft && category2.Rgt > category.Rgt)
                        counter++;
                }
                nodesWithDepth[category.Id] = counter;
            }
            ViewBag.categories = categories;
            ViewBag.order = nodesWithDepth;
            ViewBag.View = view ?? "_Details";
            IList<Lesson> lessons = null;
            if (id == 0)
            {
                lessons = Services.LessonService.GetAllLessons();
            }
            else
            {
                lessons = Services.LessonService.GetAllFromCategory(id);
            }
            if (lessons.Count > 0) {
                ViewBag.firstLesson = lessons.First();
                lessons.Remove(lessons.First());
                ViewBag.lessons = lessons; 
            }
            if (Request.IsAjaxRequest()) return PartialView("_Index");
            return View("_Index");
        }


//         GET: /Category/Details/5

        public ActionResult Details(int id = 0)
        {
            IList<Lesson> lessons = null;
            if(id == 0)
            {
                lessons = Services.LessonService.GetAllLessons();
            }
            else
            {
                lessons = Services.LessonService.GetAllFromCategory(id);
            }
            if (lessons.Count > 0) {
                ViewBag.firstLesson = lessons.First();
                lessons.Remove(lessons.First());
                ViewBag.lessons = lessons; 
            }
            if (Request.IsAjaxRequest()) {
                if (ViewBag.firstLesson != null) return PartialView("_Details");
                return Content("Wybrana kategoria jest pusta.");
            }
            return Index("_Details", id);
        }

        public ActionResult SignIn(string view)
        {
            ViewBag.View = view ?? "_LoginForm";
            if (Request.IsAjaxRequest()) return PartialView("SignIn");
            return View("SignIn");
        }

        public ActionResult LoginForm()
        {
            if (Request.IsAjaxRequest()) return PartialView("_LoginForm");
            return SignIn("_LoginForm");
        }

        public ActionResult RegisterForm()
        {
            if (Request.IsAjaxRequest()) return PartialView("_RegisterForm");
            return SignIn("_RegisterForm");
        }

        
//         GET: /Category/Create

        public ActionResult Create()
        {
            return View();
        }

        
//         POST: /Category/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        
//         GET: /Category/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        
//         POST: /Category/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        
//         GET: /Category/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        
//         POST: /Category/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TW/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8" />
        <title>ZTW</title>
        <link href="~/Content/bootstrap.css" rel="stylesheet">
        <link href="~/Content/navbar.css" rel="stylesheet">
        <link href="~/Content/userprofile.css" rel="stylesheet"/>
        <link href="~/Content/style.css" rel="stylesheet">
        @RenderSection("PageStyles", false)
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <span class="brand">ZTW</span>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li><a href="#" class="navbar-link navbar-ajax-link" data-url="@Url.Action("Index", "Home")">Start</a></li>
                        <li><a href="#" class="navbar-link navbar-ajax-link" data-url="@Url.Action("Index", "Category")">Kategorie</a></li>
                        <li>
                        @if (!Request.IsAuthenticated) {
                            <a href="#" class="navbar-link navbar-ajax-link" data-url="@Url.Action("SignIn", "Account")">Zaloguj się</a>
                        } else {
                            @Html.ActionLink("Wyloguj się", "SignOut", "Account")
                        }
                        </li>
                    </ul>
                    <div class="navbar-search pull-right" id="mainSearch">
                        <input name="query" type="text" id="searchFieldHome" class="search-query span4" placeholder="Szukaj...">
                        <div class="icon-search"></div>
                    </div>
                </div>
            </div>
            </div>
            </div>
        <div class="container" style="margin-top: 50px;">
            @if (Request.IsAuthenticated) {
                @Html.Action("UserSidePanel", "Home")
            }
            <div id="global-error-panel"></div>
            <div id="content-panel">
                @RenderBody()
            </div>
        </div>
        <div id="ajax-busy-indicator"><img src="~/Content/images/loader.gif" /></div>
        <div class="footer navbar-fixed-bottom">
            <a href="#" class="navbar-ajax-link" data-url="@Url.Action("Index", "Home")">O nas</a>
        </div>
        
        <script src="~/Scripts/jquery-2.0.1.js" type="text/javascript"></script>
        <script src="~/Scripts/jquery-ui-1.10.3.js" type="text/javascript"></script>
        <script src="~/Scripts/jquery.validate.js" type="text/javascript"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.js" type="text/javascript"></script>
        <script src="~/Scripts/jquery.filedrop.js" type="text/javascript"></script>
        <script src="~/Scripts/bootstrap.js" type="text/javascript"></script>
        <script src="~/Scripts/category.js" type="text/javascript"></script>
        <script src="~/Scripts/lesson.js" type="text/javascript"></script>
        <script src="~/Scripts/exercise.js" type="text/javascript"></script>
        <script src="~/Scripts/index.js" type="text/javascript"></script>
        <script src="~/Scripts/signIn.js" type="text/javascript"></script>
        <script src="~/Scripts/userprofile.js" type="text/javascript"></script>
        <script src="~/Scripts/tinymce.min.js" type="text/javascript"></script>
        @RenderSection("PageScripts", false)
    </body>
</html>