TW/Controllers/HomeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TW.Models.Database;
using TW.Services;

namespace TW.Controllers
{
    public class HomeController : Controller
    {
        private readonly UserProfileService _userProfileService;

        public HomeController() {
            _userProfileService = new UserProfileService();
        }

        public ActionResult Index(string query = "")
        {
            IList<Lesson> lessons = LessonService.GetNewestThree();
            ViewBag.lessons = lessons;
            IList<News> news = NewsService.GetNewestSix();
            ViewBag.news = news;
            
            if (query != "")
                return Search(query);
            if (Request.IsAjaxRequest()) return PartialView();
            return View();
        }

        public ActionResult UserSidePanel() {
            return PartialView("_UserBox", _userProfileService.GetCurrentUserProfileDetails());
        }

        public ActionResult Search(string query)
        {
            IList<Lesson> lessons = Services.LessonService.Search(query);
            ViewBag.lessons = lessons;
            return View("_Search");
        }

/*        //
        // GET: /Home/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Home/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Home/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Home/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Home/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Home/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Home/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }*/
    }
}

TW/Controllers/LessonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TW.Common;
using TW.Models;
using TW.Models.Database;
using TW.Services;

namespace TW.Controllers
{
    public class LessonController : Controller
    {
        public ActionResult Details(int id = 0, int page = 1)
        {
            Lesson lesson = null;
            IList<Page> pages = null;
            IList<Exercise> exercises = null;
            lesson = Services.LessonService.GetLesson(id);
            pages = Services.LessonService.getPagesFromLesson(id);
            exercises = Services.LessonService.getExercisesFromLesson(id);

            if (pages.Count > 0)
            {
                ViewBag.lesson = lesson;
                ViewBag.page = pages[page-1];
                ViewBag.pagesNumb = pages.Count;
                ViewBag.currentPage = page;
                ViewBag.ex = exercises.Count;
            } 
            ViewBag.View = "_Page";
            if (Request.IsAjaxRequest())
            {
                if (ViewBag.lesson != null && ViewBag.page != null) return PartialView("_Details");
                Response.StatusCode = 404;
                return Json(JsonResponseFactory.SuccessResponse("Podana lekcja nie posiada obecnie treści"));
            }
            return View("_Details");
        }

        public ActionResult Index(string view, int id = 0, int page = 1)
        {
            Lesson lesson = null;
            IList<Page> pages = null;
            lesson = Services.LessonService.GetLesson(id);
            pages = Services.LessonService.getPagesFromLesson(id);
            if (pages.Count > 0)
            {
                ViewBag.lesson = lesson;
                ViewBag.page = pages[page];
                ViewBag.pagesNumb = pages.Count;
                ViewBag.currentPage = page;
            }
            ViewBag.View = "_Page";
            if (pages.Count == 0) {
                return RedirectToAction("Index", "Category");
            }
            if (Request.IsAjaxRequest()) return PartialView("_Details");
            return View("_Details");
        }

        /*//
        // GET: /Lesson/

        public ActionResult DisplayLesson()
        {
            Lesson l = new Lesson();
            l.AddDate = new DateTime(2012, 10, 10);
            l.Content = "test";
            return View("DisplayLesson", l);
//            return View("DisplayLesson");
        }*/

//        public ActionResult AddLess
    }
}

TW/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NHibernate;
using TW.Common;
using TW.Constants;
using TW.Filters;
using TW.Models.Database;
using TW.Models.ViewModels;
using TW.Resources;
using TW.Services;
using TW.Services.Account;
using NHibernate.Linq;

namespace TW.Controllers
{
    [Authorize]
    public class UserProfileController : Controller {
        private readonly UserProfileService _userProfileService;
        private readonly FormsAuthenticationService _formsAuthenticationService;
        private readonly Random _random = new Random();

        public UserProfileController() {
            _userProfileService = new UserProfileService();
            _formsAuthenticationService = new FormsAuthenticationService();
            ViewBag.ProfileDetails = _userProfileService.GetCurrentUserProfileDetails();
            ViewBag.UpdateModel = _userProfileService.GetPrefilledUpdateModel();
        }

        public ActionResult Index(string view) {
            ViewBag.View = "_" + (view ?? "Skills");
            if (view == "AddLesson") CreateCategoryList();
            if (view == "Achievements") CreateAchievementList();
            if (view == null || view == "Skills") InitCategories();
            if (Request.IsAjaxRequest()) return PartialView("Index");
            return View("Index");
        }

        public ActionResult Inbox() {
            if (Request.IsAjaxRequest()) return PartialView("_Inbox");
            return Index("Inbox");
        }

        public ActionResult Edit() {
            if (Request.IsAjaxRequest()) return PartialView("_Edit");
            return Index("Edit");
        }

        public ActionResult Skills() {
            InitCategories();
            if (Request.IsAjaxRequest()) return PartialView("_Skills");
            return Index("Skills");
        }

        public ActionResult Achievements() {
            CreateAchievementList();
            if (Request.IsAjaxRequest()) return PartialView("_Achievements");
            return Index("Achievements");
        }

        public ActionResult AddLesson() {
            CreateCategoryList();
            if (Request.IsAjaxRequest()) return PartialView("_AddLesson");
            return Index("AddLesson");
        }

        public void InitCategories() {
            IList<Category> categories = Services.CategoryService.GetAll();
            int[] nodesWithDepth = new int[categories.Max(category1 => category1.Id) + 1];
            int[] expForCategory = new int[categories.Max(category1 => category1.Id) + 1];
            string[] skillLevel = new string[categories.Max(category1 => category1.Id) + 1];
            foreach (Category category in categories) {
                int counter = 0;
                foreach (Category category2 in categories) {
                    if (category2.Lft < category.Lft && category2.Rgt > category.Rgt)
                        counter++;
                }
                nodesWithDepth[category.Id] = counter;
                expForCategory[category.Id] = GetExpForCategoryPlaceholder(category.Id);
                skillLevel[category.Id] = GetSkillLevelForCategoryPlaceholder(category.Id, expForCategory[category.Id]);
            }
            ViewBag.categories = categories;
            ViewBag.order = nodesWithDepth;
            ViewBag.exp = expForCategory;
            ViewBag.skills = skillLevel;
        }

        private string GetSkillLevelForCategoryPlaceholder(int id, int i) {
            return "Początkujący";
        }

        private int GetExpForCategoryPlaceholder(int id) {
            return _random.Next(100);
        }

        public ActionResult AddExercise()
        {
            IList<string> types = null;
            SessionManager.InTransaction(session =>
            {
                types = session.Query<ExerciseType>()
                    .Select(category => category.Name)
                    .ToList();
            });
            IList<string> lessons = null;
            SessionManager.InTransaction(session =>
            {
                lessons = session.Query<Lesson>()
                    .Select(lesson => lesson.Name)
                    .ToList();
            });
            ViewBag.ExerciseTypeList = new SelectList(types);
            ViewBag.LessonsList = new SelectList(lessons);
            if (Request.IsAjaxRequest()) return PartialView("_AddExercise");
            return Index("AddExercise");
        }

        private void CreateCategoryList() {
            IList<string> categories = null;
            SessionManager.InTransaction(session => {
                categories = session.Query<Category>().Select(category => category.Name).ToList();
            });
            ViewBag.CategoryList = new SelectList(categories);
        }

        public void CreateAchievementList() {
            IList<Achievement> achievements = null;
            SessionManager.InTransaction(session => {
                achievements =
                    session.Query<UserAchievement>()
                           .Where(achievement => achievement.User.Id == User.UserSession().Id)
                           .Select(achievement => achievement.Achievement).ToList();
            });
            ViewBag.AchievementList = achievements;
        }

#if DEBUG
        private void SpawnAchievement(ISession session, string description, string name, string imagePath) {
            Achievement test = new Achievement() {
                Description = description,
                Name = name,
                ImagePath = imagePath
            };
            session.Save(test);
            User current = session.Get<User>(User.UserSession().Id);
            UserAchievement ua = new UserAchievement() {
                Achievement = test,
                User = current,
                ObtainDate = DateTime.Now
            };
            session.Save(ua);
        }
#endif

        [HttpPost]
        public ActionResult UpdateProfile(ProfileUpdateModel updateModel) {
            if (ModelState.IsValid) {
                bool success = _userProfileService.UpdateProfile(updateModel);
                if (success) return Json(JsonResponseFactory.SuccessResponse());
            }
            return
                Json(JsonResponseFactory.ErrorResponse(JsonHelper.GetModelErrorMessages(ModelState)));
        }

        [HttpPost]
        public ActionResult ChangePassword(PasswordChangeModel passwordChangeModel) {
            ModelState.Merge(_userProfileService.ValidatePasswordChangeModel(passwordChangeModel), "");
            if (ModelState.IsValid) {
                bool success = _formsAuthenticationService.ChangePassword(passwordChangeModel.OldPassword,
                                                           passwordChangeModel.NewPassword);
                if (success) return Json(JsonResponseFactory.SuccessResponse());
            }
            return Json(JsonResponseFactory.ErrorResponse(JsonHelper.GetModelErrorMessages(ModelState)));
        }

        [HttpPost]
        public ActionResult UploadFiles(IEnumerable<HttpPostedFileBase> files) {
            if (files.Any()) {
                var file = files.First();
                string fileName = User.UserSession().Id + Path.GetExtension(file.FileName);
                var dirPath = System.IO.Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "Content\\images\\avatar\\");
                string filePath = Path.Combine(dirPath, fileName);
                if (!Directory.Exists(dirPath)) Directory.CreateDirectory(dirPath);
                System.IO.File.WriteAllBytes(filePath, ReadData(file.InputStream));

                SessionManager.InTransaction(session => {
                    var user = session.Get<User>(User.UserSession().Id);
                    user.AvatarPath = "/Content/images/avatar/"+fileName;
                });

                return Json(JsonResponseFactory.SuccessResponse());
            }
            return Json(JsonResponseFactory.ErrorResponse("Upload obrazka nie powiódł się."));
        }

        private byte[] ReadData(Stream stream) {
            byte[] buffer = new byte[16 * 1024];

            using (MemoryStream ms = new MemoryStream()) {
                int read;
                while ((read = stream.Read(buffer, 0, buffer.Length)) > 0) {
                    ms.Write(buffer, 0, read);
                }

                return ms.ToArray();
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SubmitLesson(FormCollection formCollection) {
            SessionManager.InTransaction(session => {
                Category cat =
                    session.Query<Category>()
                           .FirstOrDefault(category => category.Name == formCollection["CategoryName"]);
                Lesson l = new Lesson() {
                    AddDate = DateTime.Now,
                    Name = formCollection["LessonName"],
                    Category = cat,
                    Content = formCollection["LessonDescription"],
                    MainImage = formCollection["ImagePath"],
                    ExperiencePoints = int.Parse(formCollection["ExpPoints"]),
                    IsAccepted = true
                };
                session.Save(l);
                string[] pageNames = Request.Form.GetValues("PageName");
                string[] pageContents = Request.Form.GetValues("content");
                for (int i = 0; i < pageNames.Length; i++) {
                    Page p = new Page() {
                        Content = pageContents[i],
                        EditDate = DateTime.Now,
                        Lesson = l,
                        Name = pageNames[i],
                        Position = i+1,
                        Visible = true,
                    };
                    session.Save(p);
                }
            });
            return Index("AddLesson");
        }

TW/Views/Home/Index.cshtml
@using TW.Models.Database
@{
    ViewBag.Title = "News";
}
        <!-- Main hero unit for a primary marketing message or call to action -->


<div id="myCarousel" class="carousel slide news-carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
    <li data-target="#myCarousel" data-slide-to="5"></li>
  </ol>
  <!-- Carousel items -->
    <div class="carousel-inner">
        
        @foreach (News news in ViewBag.news)
        {
            @Html.Raw("<div class=\"item" + (news.Id == ViewBag.news[0].Id ? " active " : "") + "\">")
            <img src="@news.BackgroundUrl" alt=""/>
            <div class="carousel-caption">
                <h4>@news.Name</h4>
                <p class="mainNewsContent">@news.Content</p>
            </div>
            @Html.Raw("</div>")
        }
    </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

<!-- Example row of columns -->
<div class="row">
    @foreach (Lesson lesson in ViewBag.lessons) {
        <div class="span4">
            <h2>@lesson.Name</h2>
            <div class="lessonMainPage"><img class="imageMainPage" style="width: 150px; float: left;" src="@lesson.MainImage"/>
            <p class="lessonContentMainPage">@lesson.Content</p></div>
            
            <p class="linkToLessonMainPage"><a class="categoryGoToLesson btn" data-url="@Url.Action("Details", "Lesson", new { id = lesson.Id })" href="#">Zobacz &raquo;</a></p>
        </div>
    }
</div>

        <hr>

        <footer>
            <p>&copy; Company 2013</p>
        </footer>

TW/Views/Home/_Search.cshtml
@using TW.Models.Database
@{
    ViewBag.Title = "_Search";
    int counter = 1;
}

<h2>Wyniki Wyszukiwania</h2>

@if (ViewBag.lessons.Count > 0)
{
    <div class="row">
        @foreach (Lesson lesson in ViewBag.lessons)
        {
            if (counter%3 == 0)
            {
                @Html.Raw("</div><div class=\"row\">")
                ;
            }
            <div class="span4">
                <h2>@lesson.Name</h2>
                <div class="lessonMainPage"><img class="imageMainPage" style="width: 150px; float: left;" src="@lesson.MainImage"/>
                    <p class="lessonContentMainPage">@lesson.Content</p></div>
            
                <p class="linkToLessonMainPage"><a class="categoryGoToLesson btn" data-url="@Url.Action("Details", "Lesson", new {id = lesson.Id})" href="#">Zobacz &raquo;</a></p>
            </div>
        }
    </div>
}
else
{
    <div class="row">
        <h4>Brak wyników wyszukiwania</h4>
    </div>
    }

TW/Views/Home/_UserBox.cshtml
@model TW.Models.ViewModels.UserProfileModel
@{
    var progress = Model.NextLevelProgressPercent + "%";
}

<div id="user-box-position-wrapper" class="user-box-hidden user-details-visible">
            <div class="fixed">
                <div id="user-box-details" class="text-center">
                    <img src="@Model.AvatarPath" alt="Avatar"/><br/>
                    <a href="#" class="user-box-link" data-url="@Url.Action("Index", "UserProfile")">@Model.DisplayableName</a><br/>
                    Poziom: @Model.CurrentLevel<br/>
                    <div class="progress progress-striped">
                  <div class="bar" style="width: @progress;"></div>
                </div>
                </div>
                <div id="user-box-bar">
                    <i class="icon-envelope user-box-link" data-url="@Url.Action("Index", "UserProfile", new {view = "Inbox"})"></i>
                    <i class="icon-wrench user-box-profile-edit-ajax-link" data-url="@Url.Action("Index", "UserProfile", new {view = "Edit"})"></i>
                    <i class="icon-arrow-right user-details-toggle"></i>
                </div>
            </div>
        </div>